import { HideViewSideBarContextProvider } from "@/ContextApi/HideViewSideBarContext";
import "./globals.css";
import { TableListContextContextProvider } from "@/ContextApi/TableListContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <HideViewSideBarContextProvider>
        <TableListContextContextProvider>
      <body>{children}</body>
      </TableListContextContextProvider>
      </HideViewSideBarContextProvider>
      
    </html>
  );
}
