import { HideViewSideBarContextProvider } from "@/ContextApi/HideViewSideBarContext";
import "./globals.css";
import { TableListContextContextProvider } from "@/ContextApi/TableListContext";
import { ProductAddContextProvider } from "@/ContextApi/ProductAddContext";
import { ProductEditContextProvider } from "@/ContextApi/ProductEditContext";
import { ProductDeleteContextProvider } from "@/ContextApi/ProductDeleteContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="./styles.css" />
      </head>
      <HideViewSideBarContextProvider>
        <TableListContextContextProvider>

          <ProductEditContextProvider>
            <ProductDeleteContextProvider>
          <ProductAddContextProvider>
            <body>{children}</body>
          </ProductAddContextProvider>
          </ProductDeleteContextProvider>
          </ProductEditContextProvider>
        </TableListContextContextProvider>
      </HideViewSideBarContextProvider>
    </html>
  );
}
