import { HideViewSideBarContextProvider } from "@/ContextApi/HideViewSideBarContext";
import "./globals.css";
import { TableListContextContextProvider } from "@/ContextApi/TableListContext";
import { ProductAddContextProvider } from "@/ContextApi/ProductAddContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <HideViewSideBarContextProvider>
        <TableListContextContextProvider>
          <ProductAddContextProvider>
            <body>{children}</body>
          </ProductAddContextProvider>
        </TableListContextContextProvider>
      </HideViewSideBarContextProvider>
    </html>
  );
}
